name: Gradle / Validate wrapper

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/gradl–µ-wrapper.jar'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
